CREATE DATABASE IF NOT EXISTS WordPress;
CREATE USER IF NOT EXISTS 'nseniak'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON WordPress.* TO 'nseniak'@'%' IDENTIFIED BY '123';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
FLUSH PRIVILEGES;